// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZfmoTKBPMtemEgKCVH2BIMLJXJuYkNuw',
    appId: '1:183700461034:web:2d554bc4da1954eb58ce93',
    messagingSenderId: '183700461034',
    projectId: 'tekzo-eb301',
    authDomain: 'tekzo-eb301.firebaseapp.com',
    storageBucket: 'tekzo-eb301.firebasestorage.app',
    measurementId: 'G-3BB4MK7F6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjEf8lkV90zlebRDMnIk5xodIv0_02vDA',
    appId: '1:183700461034:android:e5ffce35270076ff58ce93',
    messagingSenderId: '183700461034',
    projectId: 'tekzo-eb301',
    storageBucket: 'tekzo-eb301.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZfmoTKBPMtemEgKCVH2BIMLJXJuYkNuw',
    appId: '1:183700461034:web:f4ffd52ab3aca28658ce93',
    messagingSenderId: '183700461034',
    projectId: 'tekzo-eb301',
    authDomain: 'tekzo-eb301.firebaseapp.com',
    storageBucket: 'tekzo-eb301.firebasestorage.app',
    measurementId: 'G-N5VKY5FGQ6',
  );
}
